- name: ensure ntpd is at the latest version
  yum: pkg=ntp state=latest
  notify:
    - restart ntpd

- name: Install yum-utils
  become: yes
  yum:
    name: ['yum-utils']

- name: "Enable extras"
  shell:
    yum-config-manager --enable "CentOS-7 - Extras"

- name: Add docker-ce-stable repo
  yum_repository:
    name: docker-ce
    description: docker-ce stable repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes

- name: Add kubernetes repo
  yum_repository:
    name: kubernetes
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes
