---
- name: display post install message
  debug: msg="{{ post_install.split('\n') }}"
  vars:
    post_install: |
      Things to know:
        - kubeconfig file has been copied to ~/.kube on your local machine
        - see working nodes run: kubectl get nodes
  when: k8s.config.copy_to_ansible_host
