k8s:
  version: 1.15.1
  cluster_name: "test-cluster"
  token: "lr8z7r.6u3mibktxl23d188"
  # For flannel use 10.244.0.0/16, calico uses 192.168.0.0/16
  pod_network: "10.244.0.0/16"
  flannel:
    install: true
    interface: "eth1"
  calico:
    install: false

docker:
  install: true
  version: 18.09.8

keepalived:
  install: true
  ip: 172.16.35.100
  interface: "eth1"
  vrid: 100
  adv_interval: 1

etcd:
  install: true
  version: "3.3.13"
  interface: "eth1"

# Create masters
masters:
  install: true

# Install haproxy
haproxy:
  install: true

# CNI plugins
cni:
  version: "0.8.1"
