---
- name: Create kubernetes cert directory
  file:
    path: /etc/kubernetes/pki
    state: directory

- name: Slurp CA certificate from ansible host
  slurp:
    src: "/opt/kubernetes/pki/{{ item }}"
  with_items:
    - admin-key.pem
    - admin.pem
    - apiserver-key.pem
    - apiserver.pem
    - ca-key.pem
    - ca.pem
    - controller-key.pem
    - controller.pem
    - etcd-key.pem
    - etcd.pem
    - front-proxy-client-key.pem
    - front-proxy-client.pem
    - kubelet-client-key.pem
    - kubelet-client.pem
    - scheduler-key.pem
    - scheduler.pem
    - node.pem
    - node-key.pem
  register: pki_certs
  run_once: true
  delegate_to: "{{ groups['main'][0] }}"

- name: Write CA certificate from ansible host to disk
  copy:
    dest: "/etc/kubernetes/pki/{{ item.item }}"
    content: "{{ item.content | b64decode }}"
  register: openssl_cert
  with_items: "{{ pki_certs.results }}"
