- name: Install docker dependencies
  become: yes
  yum:
    name: ["device-mapper-persistent-data", "lvm2"]

- name: Install Docker-CE engine
  yum:
    name: docker-ce-{{ docker_version }}
    state: installed

- name: Create /etc/docker/ folder
  file:
    path: "/etc/docker/ "
    state: directory
    owner: "root"

- name: Configure additional engine options
  copy:
    content: "{{ docker_ce_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: 0644
  when: docker_ce_daemon_options is defined

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes
