---
- name: Add docker-ce-stable repo
  yum_repository:
    name: docker-ce
    description: docker-ce stable repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes

- name: Install Docker dependencies on {{ ansible_distribution }}
  package:
    name: ["yum-utils", "lvm2", "device-mapper-persistent-data"]
    state: latest
    update_cache: yes

- name: Install Docker repo on CentOS
  command: "yum-config-manager --add-repo {{ docker_repo | default('https://download.docker.com/linux/centos/docker-ce.repo') }}"
  when: ansible_distribution == "CentOS"

- name: Install Docker on {{ ansible_distribution }}
  package:
    name: "docker-ce-{{ docker.version }}"
    state: latest
    update_cache: yes

- name: Create kubernetes config directory
  file:
    path: "/etc/docker"
    state: directory

- name: Copy docker.json file
  template:
    src: docker.json.j2
    dest: "/etc/docker/daemon.json"
  register: docker_daemon

- name: Start Docker Daemon
  service:
    name: docker
    enabled: yes
    state: restarted
    daemon_reload: yes
