- hosts: all
  become: yes
  roles:
    - role: requirements
      when: ansible_os_family == "RedHat"
  tags:
    - yum-repo

- hosts: all
  become: yes
  roles:
    - role: kubeadm-requirements
      when: ansible_os_family == "RedHat"
  tags:
    - kubeadm-requirements

- hosts: all
  become: yes
  roles:
    - { role: docker, when: ansible_os_family == "RedHat" and docker.install }
  tags:
    - docker

- hosts: all
  become: yes
  roles:
    - { role: haproxy, when: ansible_os_family == "RedHat" and haproxy.install }
  tags:
    - haproxy

- hosts: all
  become: yes
  roles:
    - { role: keepalived, when: ansible_os_family == "RedHat" and keepalived.install }
  tags:
    - keepalived

- hosts: masters
  become: yes
  roles:
    - { role: etcd, when: ansible_os_family == "RedHat" and etcd.install }
  tags:
    - etcd

- hosts: masters
  become: yes
  roles:
    - { role: masters, when: ansible_os_family == "RedHat" and masters.install }
  tags:
    - masters

- hosts: 127.0.0.1
  gather_facts: false
  become: false
  roles:
    - { role: addons, when: masters.install }
  tags:
    - addons

- hosts: 127.0.0.1
  become: false
  gather_facts: false
  roles:
    - { role: post-install, when: masters.install }
  tags:
    - post-install
